export const dummyPlaces = [
  {
    id: '1',
    title: 'Y Restoran',
    image: 'https://placehold.co/300x200?text=Coffee',
    rating: 4.2,
    reviewCount: 100,
    distance: '1.2 km',
    isSuper: true,
    hasCampaign: true,
    discountRate: 15, // 15% discount
  },
  {
    id: '2',
    title: 'Z Cafe',
    image: 'https://placehold.co/300x200?text=Cafe',
    rating: 4.5,
    reviewCount: 80,
    distance: '800 m',
    isSuper: false,
    hasCampaign: false,
  },
  {
    id: '3',
    title: 'Lahmacun Corner',
    image: 'https://placehold.co/300x200?text=Lahmacun',
    rating: 3.8,
    reviewCount: 45,
    distance: '2.5 km',
    isSuper: false,
    hasCampaign: true,
    discountRate: 20,
  },
  {
    id: '4',
    title: 'Burger Time',
    image: 'https://placehold.co/300x200?text=Burger',
    rating: 4.7,
    reviewCount: 210,
    distance: '600 m',
    isSuper: true,
    hasCampaign: false,
  },
  {
    id: '5',
    title: 'Tatlıcı Abi',
    image: 'https://placehold.co/300x200?text=Baklava',
    rating: 4.9,
    reviewCount: 300,
    distance: '1.0 km',
    isSuper: false,
    hasCampaign: true,
    discountRate: 10,
  },
  {
    id: '6',
    title: 'Balıkçı Mahmut',
    image: 'https://placehold.co/300x200?text=Balık',
    rating: 4.1,
    reviewCount: 110,
    distance: '1.8 km',
    isSuper: false,
    hasCampaign: false,
  },
  {
    id: '7',
    title: 'Dünyanın En Süper İyi Köftecisi',
    image: 'https://placehold.co/300x200?text=Köfte',
    rating: 4.6,
    reviewCount: 180,
    distance: '900 m',
    isSuper: true,
    hasCampaign: true,
    discountRate: 25,
  },
];
