// dummyData.js
export const dummyPlaces = [
  {
    id: '1',
    title: 'Y Restoran',
    category: 'COFFEE',
    image: 'https://placehold.co/300x200/8B4513/FFFFFF?text=Coffee',
    rating: 4.2,
    reviewCount: 100,
    distance: '1.2 km',
    isSuper: true,
    hasCampaign: true,
    discountRate: 15,
  },
  {
    id: '2',
    title: 'Z Cafe',
    category: 'CAFE',
    image: 'https://placehold.co/300x200/6F4E37/FFFFFF?text=Cafe',
    rating: 4.5,
    reviewCount: 80,
    distance: '800 m',
    isSuper: false,
    hasCampaign: false,
  },
  {
    id: '3',
    title: 'Lahmacun Corner',
    category: 'DURGER',
    image: 'https://placehold.co/300x200/CD853F/FFFFFF?text=Lahmacun',
    rating: 3.8,
    reviewCount: 45,
    distance: '2.5 km',
    isSuper: false,
    hasCampaign: true,
    discountRate: 20,
  },
  {
    id: '4',
    title: 'Burger Time',
    category: 'BURGER',
    image: 'https://placehold.co/300x200/800000/FFFFFF?text=Burger',
    rating: 4.7,
    reviewCount: 210,
    distance: '600 m',
    isSuper: true,
    hasCampaign: false,
  },
  {
    id: '5',
    title: 'Tatlıcı Abi',
    category: 'DESERTS',
    image: 'https://placehold.co/300x200/FF6347/FFFFFF?text=Baklava',
    rating: 4.9,
    reviewCount: 300,
    distance: '1.0 km',
    isSuper: false,
    hasCampaign: true,
    discountRate: 10,
  },
  {
    id: '6',
    title: 'Balıkçı Mahmut',
    category: 'SEAFOOD',
    image: 'https://placehold.co/300x200/4682B4/FFFFFF?text=Balık',
    rating: 4.1,
    reviewCount: 110,
    distance: '1.8 km',
    isSuper: false,
    hasCampaign: false,
  },
  {
    id: '7',
    title: 'Dünyanın En Süper İyi Köftecisi',
    category: 'DURGER',
    image: 'https://placehold.co/300x200/A0522D/FFFFFF?text=Köfte',
    rating: 4.6,
    reviewCount: 180,
    distance: '900 m',
    isSuper: true,
    hasCampaign: true,
    discountRate: 25,
  },
  {
    id: '8',
    title: 'Pizza Napoli',
    category: 'PIZZA',
    image: 'https://placehold.co/300x200/DC143C/FFFFFF?text=Pizza',
    rating: 4.3,
    reviewCount: 150,
    distance: '1.5 km',
    isSuper: false,
    hasCampaign: true,
    discountRate: 15,
  },
  {
    id: '9',
    title: 'Kebap Sarayı',
    category: 'KEBAP',
    image: 'https://placehold.co/300x200/8B0000/FFFFFF?text=Kebap',
    rating: 4.8,
    reviewCount: 220,
    distance: '700 m',
    isSuper: true,
    hasCampaign: false,
  },
];
